### ISSUE TITLE
You don't have permission to access "http://api.ec.nintendo.com/v1/price?" on this server.

### ISSUE THREAD

**Issue by dvgamerr** [lmmfranco/nintendo-switch-eshop#11]
```html
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http://api.ec.nintendo.com/v1/price?" on this server.<P>
Reference #18.5402a46e.1521957632.26bea562
</BODY>
</HTML>
```
Error at
```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request.get [as _callback] (C:\Users\GitHub.com\co.consolegamer\node_modules\nintendo-switch-eshop\index.js:367:37)
    at Request.self.callback (C:\Users\GitHub.com\co.consolegamer\node_modules\request\request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (C:\Users\GitHub.com\co.consolegamer\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (C:\Users\GitHub.com\co.consolegamer\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by lmmfranco** [comment]
It seems there is now some throttling in place, sending multiple requests will get you blocked for some minutes. I'll work on that as soon as I can.

**Comment by reinvanimschoot** [comment]
Is there more information on the exact limits that Nintendo is putting up? Does the block time get incremented when you query more rapidly?

**Comment by Favna** [comment]
Updating this issue as part of my rework of the lib into TypeScript as per #16, the lib will throw a graceful error however other than that there is not much we can do about it except encourage the end-users to not spam the Nintendo API. 

Please do note that it is not yet available at time of writing, some final quirks still need to be addressed in the rework.
